version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
volumes:
  postgres:
